In [2]:
import numpy as np

## Datatypes and Attributes

In [24]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [3]:
type(a1)

numpy.ndarray

In [25]:
a2 = np.array([[1,2,3],
               [4,5,6]])

In [7]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[21,23,21],
              [2,3,1],
               [4,3,6]]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[21, 23, 21],
        [ 2,  3,  1],
        [ 4,  3,  6]]])

In [10]:
a1.shape

(4,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a1.ndim

1

In [14]:
a2.ndim

2

In [15]:
a3.ndim

3

In [16]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [17]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [18]:
a1.size,a2.size,a3.size

(4, 6, 18)

In [19]:
import pandas as pd

In [20]:
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## 2. Create Numpys Arrays

In [23]:
ones = np.ones((2,3), dtype=np.int8)

In [24]:
ones

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [25]:
type(ones)

numpy.ndarray

In [26]:
zeros = np.zeros((2,3))

In [27]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
zeros.dtype

dtype('float64')

In [29]:
type(zeros)

numpy.ndarray

In [3]:
range_array = np.arange(0, 12, 2)
range_array

array([ 0,  2,  4,  6,  8, 10])

In [8]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[5, 9, 4, 0, 3],
       [1, 4, 5, 4, 1],
       [2, 1, 2, 9, 8]])

In [10]:
random_array2 = np.random.random(size=(3, 5))
random_array2

array([[0.9994253 , 0.640759  , 0.90023066, 0.07656459, 0.86483456],
       [0.56508222, 0.72162704, 0.57251854, 0.89972399, 0.13005483],
       [0.01435303, 0.35469789, 0.07589623, 0.90369853, 0.43144446]])

In [11]:
random_array3 = np.random.rand(2,3)
random_array3

array([[0.9018126 , 0.37890415, 0.16235905],
       [0.87084803, 0.17818178, 0.8971552 ]])

In [14]:
#Pseudo ramdom Errors
seed = np.random.seed(seed=99999)
random_array4 = np.random.randint(10, size=(5,3))
random_array4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [18]:
np.random.seed(7)
random_array5 = np.random.random((5,3))
random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## Viewing arrays and matrices

In [19]:
random_array4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [20]:
np.unique(random_array4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [21]:
np.unique(random_array5)

array([0.06593635, 0.07205113, 0.07630829, 0.26843898, 0.2881456 ,
       0.38094113, 0.43840923, 0.4998825 , 0.50112046, 0.53849587,
       0.67923   , 0.72346518, 0.77991879, 0.80373904, 0.97798951])

In [22]:
np.unique(random_array2)

array([0.01435303, 0.07589623, 0.07656459, 0.13005483, 0.35469789,
       0.43144446, 0.56508222, 0.57251854, 0.640759  , 0.72162704,
       0.86483456, 0.89972399, 0.90023066, 0.90369853, 0.9994253 ])

In [27]:
a1

array([1, 2, 3, 4])

In [28]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[21, 23, 21],
        [ 2,  3,  1],
        [ 4,  3,  6]]])

In [30]:
np.unique(a3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 21, 23])

In [31]:
a3.shape

(2, 3, 3)

In [32]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
a3[0][2][1]

8

In [46]:
a3[0][0][:2]

array([1, 2])

In [53]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[21, 23, 21],
        [ 2,  3,  1],
        [ 4,  3,  6]]])

In [66]:
a3[1, 0, 2]

21

In [67]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [71]:
a4[1,1,0]

array([9, 9, 0, 6, 2])

## Manipulating Array

### Arithmetic

In [72]:
a1

array([1, 2, 3, 4])

In [96]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [77]:
a1 + ones

array([2., 3., 4., 5.])

In [78]:
a1 - ones

array([0., 1., 2., 3.])

In [79]:
a1 * ones

array([1., 2., 3., 4.])

In [80]:
a1 / ones

array([1., 2., 3., 4.])

In [88]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [82]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
a1 / a2

array([[1.  , 1.  , 1.  ],
       [0.25, 0.4 , 0.5 ]])

In [90]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [91]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[21, 23, 21],
        [ 2,  3,  1],
        [ 4,  3,  6]]])

In [100]:
ones / a2

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [105]:
a2.shape

(2, 3)

In [107]:
a3.shape

(2, 3, 3)

In [101]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [113]:
a6 = np.reshape(a3, (6,3))

In [117]:
a7 = np.reshape(a2, (1,6))

In [119]:
 a7

array([[1, 2, 3, 4, 5, 6]])

### Aggregation 

In [120]:
sum(a1)

6

In [121]:
np.sum(a1)

6

In [122]:
np.sum(a2)

21

In [123]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
sum(a2)

array([5, 7, 9])

In [125]:
sum(a3)

array([[22, 25, 24],
       [ 6,  8,  7],
       [11, 11, 15]])

In [126]:
np.sum(a3)

129

In [127]:
a3 * ones

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[21., 23., 21.],
        [ 2.,  3.,  1.],
        [ 4.,  3.,  6.]]])

In [128]:
massive_array = np.random.random(10000)
massive_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [129]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

5.19 ms ± 194 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
42.7 µs ± 4.33 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [130]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
np.sum(a2)/6

3.5

In [134]:
np.mean(a2)

3.5

In [135]:
np.max(a2)

6

In [136]:
 np.std(a2)

1.707825127659933

In [137]:
np.var(a2)

2.9166666666666665

In [138]:
np.sqrt(np.var(a2))

1.707825127659933

In [141]:
# Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2,4,6,8,10])

In [142]:
np.var(high_var_array), np.var(low_var_array)

(4296133.472222221, 8.0)

## Reshape and Tranpose

In [144]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[21, 23, 21],
        [ 2,  3,  1],
        [ 4,  3,  6]]])

In [150]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [151]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[21, 23, 21],
        [ 2,  3,  1],
        [ 4,  3,  6]]])

In [152]:
a2_a3 = a2_reshape * a3

In [153]:
a2_a3.shape

(2, 3, 3)

In [154]:
a1

array([1, 2, 3])

In [155]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [156]:
a2_reshape

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [158]:
# Transpose
a2.transpose().shape

(3, 2)

In [159]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[21, 23, 21],
        [ 2,  3,  1],
        [ 4,  3,  6]]])

In [161]:
a3.T

array([[[ 1, 21],
        [ 4,  2],
        [ 7,  4]],

       [[ 2, 23],
        [ 5,  3],
        [ 8,  3]],

       [[ 3, 21],
        [ 6,  1],
        [ 9,  6]]])

In [162]:
a3.T.shape

(3, 3, 2)

## Dot Product 

In [165]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [166]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [167]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [170]:
# Element-wise Multiplication (Hadamard Product)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [171]:
# Dot Product
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [173]:
mat1T = mat1.T
mat1T.shape

(3, 5)

In [174]:
np.dot(mat1T, mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

In [175]:
mat3 = np.dot(mat1.T, mat2)
np.sum(mat3)

941

In [176]:
mat4 = np.dot(mat1, mat2.T)
np.sum(mat4)

1779

## Dot Product Example

In [177]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [178]:
import pandas as pd

In [183]:
# weekly sales Dataframe
weekly_sales = pd.DataFrame(sales_amounts, index=['Mon', 'Tues', 'Wed', 'Thurs', 'Fri'], columns=['Almond Butter', 'Peanut Butter', 'Cashew Butter'])

In [207]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

In [185]:
# Prices Array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [187]:
# Butter prices Dataframe
butter_prices = pd.DataFrame(prices.reshape((1,3)), index=['Price'], columns=['Almond Butter', 'Peanut Butter', 'Cashew Butter'])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [191]:
prices.shape

(3,)

In [190]:
sales_amounts.shape

(5, 3)

In [197]:
total_amounts = prices.dot(sales_amounts.T)
total_amounts

array([240, 138, 458, 232, 142])

In [198]:
weekly_sales.shape,butter_prices.shape

((5, 3), (1, 3))

In [200]:
daily_sales = weekly_sales.dot(butter_prices.T)
daily_sales

Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142

In [201]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [202]:
weekly_sales["Total ($)"] = daily_sales

In [203]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

## Comparison Operatiors

In [208]:
a1

array([1, 2, 3])

In [209]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [211]:
a2 >= a1

array([[ True,  True,  True],
       [ True,  True,  True]])

In [212]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

## Sorting Arrays

In [213]:
random_array

array([[5, 9, 4, 0, 3],
       [1, 4, 5, 4, 1],
       [2, 1, 2, 9, 8]])

In [219]:
np.sort(random_array, axis=0)

array([[1, 1, 2, 0, 1],
       [2, 4, 4, 4, 3],
       [5, 9, 5, 9, 8]])

In [220]:
random_array

array([[5, 9, 4, 0, 3],
       [1, 4, 5, 4, 1],
       [2, 1, 2, 9, 8]])

In [221]:
np.argsort(random_array)

array([[3, 4, 2, 0, 1],
       [0, 4, 1, 3, 2],
       [1, 0, 2, 4, 3]], dtype=int64)

In [223]:
np.argmax(random_array)

1

## Practical image Example

<img src='images/panda.png' />

In [226]:
# Turn Image into numpy array
from matplotlib.image import imread
panda = imread('images/panda.png')
panda.shape

(2330, 3500, 3)

In [227]:
panda.size, panda.ndim

(24465000, 3)

In [230]:
panda[:2]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]], dtype=float32)

<img src='images/car-photo.png' />

In [231]:
car = imread('images/car-photo.png')
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

<img src='images/dog-photo.png' />

In [232]:
dog = imread('images/dog-photo.png')
dog[:1]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]]], dtype=float32)